# Generated by Django 5.0.3 on 2024-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="title",
            field=models.CharField(default="lion", max_length=200),
        ),
    ]
